# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'srp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  # Pods for srp

  target 'srpTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'srp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for srp-tvOS

  target 'srp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
